### PR TITLE
feat: kudos.txt

### PR DESCRIPTION
**Pull request by dschier-wtd**
Adding kudos.txt, which is quite stable for now and some styleguide stuff.

- update: README.md
- update: docs/SYTELGUIDE.md
- update: docs/CONTRIBUTING.md
- update: kudos.txt and templates/kudos.txt.j2

Resolves: #15
See also: #3

### CODE REVIEW

**Comment by daniel-schier** [comment]
github cannot display inline svg. will fix this asap.

**Comment by daniel-schier** [comment]
meh... github also strips css...

will add some example images for the colors.

**Comment by daniel-schier** [comment]
@TheRojam this one is ready for review.

**Comment by TheRojam** [comment]
@daniel-wtd i will take a look

**Review by TheRojam — APPROVED** [review]
I did not see anything, that this request deny.
approved

**Pull request merged**
